name = "api-helper"
compatibility_date = "2025-02-18"
main = "workers/index.js"

[[d1_databases]]
binding = "DB"
database_name = "api-helper"
database_id = "8ff9889f-27d0-4476-bcb2-007a82e15cd1"

routes = [
    { pattern = "apihelp.hasty.systems/*", zone = "hasty.systems"}
]